# Netlify Configuration File
# This configures how Netlify builds and deploys your site

[build]
  # Vite builds to the dist directory
  publish = "dist"

  # Build command runs Vite build which copies everything to dist
  command = "npm run build"

# Redirect rules - only redirect when file not found
# This allows HTML pages and static assets to be served normally
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.html"
  [headers.values]
    # Don't cache HTML files - force revalidation
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache JS/CSS for 1 day with revalidation
    Cache-Control = "public, max-age=86400, must-revalidate"

[[headers]]
  for = "/*.png"
  [headers.values]
    # Cache images for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.PNG"
  [headers.values]
    # Cache images for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    # Cache images for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    # Cache images for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    # Cache SVG for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    # Cache JavaScript for 1 day
    Cache-Control = "public, max-age=86400, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    # Cache CSS for 1 day
    Cache-Control = "public, max-age=86400, must-revalidate"
